sudo: true
language: emacs-lisp
env:
  - EMACS_BINARY=emacs-24.3-bin PATH=$HOME/.evm/bin:$PATH MAKE_TEST=test
  - EMACS_BINARY=emacs-24.4-bin PATH=$HOME/.evm/bin:$PATH MAKE_TEST=test
  - EMACS_BINARY=emacs-24.5-bin PATH=$HOME/.evm/bin:$PATH MAKE_TEST=test
  - EMACS_BINARY=emacs-snapshot MAKE_TEST=test
  - MAKE_TEST=test-bytecomp EMACS_BINARY=emacs-24.5-bin PATH=$HOME/.evm/bin:$PATH

before_script:
  - sh vagrant/provision.sh
  - make elpa
script:
  - make $MAKE_TEST
