sudo: true
language: emacs-lisp
env:
  - EMACS_BINARY=emacs-24.3-bin PATH=$HOME/.evm/bin:$PATH
  - EMACS_BINARY=emacs-24.4-bin PATH=$HOME/.evm/bin:$PATH
  - EMACS_BINARY=emacs-24.5-bin PATH=$HOME/.evm/bin:$PATH
  - EMACS_BINARY=emacs-snapshot

before_script:
  - sh vagrant/provision.sh
  - make elpa
script:
  - make test
